version: 2
jobs:
  build:

    working_directory: ~/jooq-playground

    docker:
      - image: circleci/openjdk:11.0.1-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: jooq-playground-{{ checksum "build.gradle" }}

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jooq-playground-{{ checksum "build.gradle" }}

      - run: ./gradlew build
